apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-marketplace
  namespace: watchlist
spec:
  selector:
    matchLabels:
      app: movies-marketplace
  template:
    metadata: 
      labels: 
        app: movies-marketplace
    spec:
      containers:
      - name: movies-marketplace
        image: monarene/movies-marketplace:develop
        resources:
          requests:
            cpu: "500m"
            memory: "128Mi"
          limits:
            cpu: "1000m"
            memory: "256Mi"
        ports:
        - containerPort: 80