apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-store
  namespace: watchlist
spec:
  selector:
    matchLabels:
      app: movies-store
  template:
    metadata: 
      labels: 
        app: movies-store
    spec:
      containers:
      - name: movies-store
        image: monarene/movie-store:develop
        resources:
          requests:
            cpu: "500m"
            memory: "128Mi"
          limits:
            cpu: "1000m"
            memory: "256Mi"
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: mongodb.watchlist.svc.cluster.local